# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zsm < Formula
  desc "TUI session manager for zmx"
  homepage "https://github.com/mdsakalu/zmx-session-manager"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v0.3.1/zmx-session-manager_0.3.1_darwin_amd64.tar.gz"
      sha256 "2eeec83362a30687ef5d6b41a18bd64b26a422acf597b820a7a4e13a3b36239b"

      def install
        bin.install "zsm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v0.3.1/zmx-session-manager_0.3.1_darwin_arm64.tar.gz"
      sha256 "1927e28f6f76a8274d4bcdded9a84f23dccd8c0942c19c0da6c97f895e022381"

      def install
        bin.install "zsm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v0.3.1/zmx-session-manager_0.3.1_linux_amd64.tar.gz"
      sha256 "57acda67a0e5b793511660e22c34f23ad550691bb942562f3224f69c9ca290f3"
      def install
        bin.install "zsm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v0.3.1/zmx-session-manager_0.3.1_linux_arm64.tar.gz"
      sha256 "3e4ba2b4352b8b21e0b71bdc6fc36aaa5b35a951df2981326aa5d51be7543731"
      def install
        bin.install "zsm"
      end
    end
  end
end
