# This file was generated by GoReleaser. DO NOT EDIT.
cask "zsm" do
  name "zsm"
  desc "TUI session manager for zmx"
  homepage "https://github.com/mdsakalu/zmx-session-manager"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zsm"

  on_macos do
    on_intel do
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v#{version}/zmx-session-manager_#{version}_darwin_amd64.tar.gz"
      sha256 "5ded961ec28b83aae026325382d14959938ea70f55331af3dc7860413887df31"
    end
    on_arm do
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v#{version}/zmx-session-manager_#{version}_darwin_arm64.tar.gz"
      sha256 "dd2ed0d1528542f95909271639d998f4d94aa5832303fba4116cab5b7220c15c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v#{version}/zmx-session-manager_#{version}_linux_amd64.tar.gz"
      sha256 "b054e3cae5664dc1081447deb44e054c73ae4c6d98de8a97534d4d8aba16755b"
    end
    on_arm do
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v#{version}/zmx-session-manager_#{version}_linux_arm64.tar.gz"
      sha256 "2c40c4e06acc46a0aff80e872ac5cebe1df2ccfea63f53ab0379ea7d9a754a13"
    end
  end

  # No zap stanza required
end
