# This file was generated by GoReleaser. DO NOT EDIT.
cask "zsm" do
  name "zsm"
  desc "TUI session manager for zmx"
  homepage "https://github.com/mdsakalu/zmx-session-manager"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zsm"

  on_macos do
    on_intel do
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v#{version}/zmx-session-manager_#{version}_darwin_amd64.tar.gz"
      sha256 "a94f281cd0076799238156df1360ccc374a7461294ee3f0f9eab3d7cd2528b41"
    end
    on_arm do
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v#{version}/zmx-session-manager_#{version}_darwin_arm64.tar.gz"
      sha256 "a4e1de3c446999e80c9e73a0c3a9a2002e14450d8b4e03b59f12d279519ad141"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v#{version}/zmx-session-manager_#{version}_linux_amd64.tar.gz"
      sha256 "ced37b6c5fa38ceed37a266aa3219c16b41053f050bf56c35f5ea3ecc40e9eb7"
    end
    on_arm do
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v#{version}/zmx-session-manager_#{version}_linux_arm64.tar.gz"
      sha256 "fc40c782381184403bc9e79ea236fc3d952c2e9e9f698a9df305a51969d3f089"
    end
  end

  # No zap stanza required
end
