# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zsm < Formula
  desc "TUI session manager for zmx"
  homepage "https://github.com/mdsakalu/zmx-session-manager"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v0.3.2/zmx-session-manager_0.3.2_darwin_amd64.tar.gz"
      sha256 "f3756303b279795e2af681340ef5371d29c91f1145e2dd2de2bd0717a37db4d2"

      def install
        bin.install "zsm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v0.3.2/zmx-session-manager_0.3.2_darwin_arm64.tar.gz"
      sha256 "36e9749d956fe6e5b0a4038da82bccc486326d8b6083e2a745d9d58ea255af33"

      def install
        bin.install "zsm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v0.3.2/zmx-session-manager_0.3.2_linux_amd64.tar.gz"
      sha256 "92c5b0e4d55586bbe87ca56c899afe86b5e7b92af7bb37b49c8985905e15ba8e"
      def install
        bin.install "zsm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdsakalu/zmx-session-manager/releases/download/v0.3.2/zmx-session-manager_0.3.2_linux_arm64.tar.gz"
      sha256 "b2abc5803e9dd0c5911d2253493118a618a38f2cd2a21d18a7761f6fe6cfae15"
      def install
        bin.install "zsm"
      end
    end
  end
end
